"""Knowledge Base domain entities — SQLModel tables for document and chunk storage."""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import Optional

from pgvector.sqlalchemy import Vector
from sqlalchemy import BigInteger, Column, DateTime, ForeignKey, Text
from sqlalchemy.orm import mapped_column
from sqlmodel import Field, SQLModel


class KnowledgeBaseDocument(SQLModel, table=True):
    """HR knowledge base document metadata.

    Tracks uploaded PDF/DOCX files and their ingestion status.
    The actual file bytes are stored in MinIO (bucket ``knowledge-base``).
    Chunks are stored in :class:`KnowledgeBaseChunk`.
    """

    __tablename__ = "hr_knowledge_base_documents"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    display_name: str = Field(max_length=500)
    category: str = Field(default="general", max_length=100)
    file_name: str = Field(max_length=500)
    storage_path: str = Field(max_length=1000)
    file_size: int = Field(sa_type=BigInteger)
    mime_type: str = Field(max_length=200)
    status: str = Field(
        default="pending",
        max_length=20,
    )
    error_message: Optional[str] = Field(default=None)
    chunk_count: int = Field(default=0)
    description: Optional[str] = Field(default=None, sa_column=Column(Text, nullable=True))
    kb_type: str = Field(default="hr", max_length=20)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )


class KnowledgeBaseChunk(SQLModel, table=True):
    """A text chunk with its pgvector embedding for a knowledge base document.

    Each document is split into chunks of ~512 tokens (overlap 50).
    The ``embedding`` column stores a 1024-dimensional vector generated by
    the vroom-embedding service (AITeamVN/Vietnamese_Embedding_v2).
    """

    __tablename__ = "hr_knowledge_base_chunks"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    document_id: uuid.UUID = Field(
        foreign_key="hr_knowledge_base_documents.id",
    )
    chunk_index: int
    content: str = Field(sa_column=Column(Text, nullable=False))
    embedding: Optional[list[float]] = Field(
        default=None,
        sa_column=Column(Vector(1024), nullable=True),
    )
    token_count: int = Field(default=0)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )


class EmployeeKnowledgeBaseDocument(SQLModel, table=True):
    """Employee knowledge base document metadata.

    Tracks uploaded PDF/DOCX files and their ingestion status for the Employee KB.
    The actual file bytes are stored in MinIO (bucket ``knowledge-base``).
    Chunks are stored in :class:`EmployeeKnowledgeBaseChunk`.

    Physically separate from HR KB tables for security isolation (Issue #260).
    """

    __tablename__ = "employee_knowledge_base_documents"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    display_name: str = Field(max_length=500)
    category: str = Field(default="general", max_length=100)
    file_name: str = Field(max_length=500)
    storage_path: str = Field(max_length=1000)
    file_size: int = Field(sa_type=BigInteger)
    mime_type: str = Field(max_length=200)
    status: str = Field(
        default="pending",
        max_length=20,
    )
    error_message: Optional[str] = Field(default=None)
    chunk_count: int = Field(default=0)
    description: Optional[str] = Field(default=None, sa_column=Column(Text, nullable=True))
    kb_type: str = Field(default="employee", max_length=20)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )


class EmployeeKnowledgeBaseChunk(SQLModel, table=True):
    """A text chunk with its pgvector embedding for an Employee KB document.

    Each document is split into chunks of ~512 tokens (overlap 50).
    The ``embedding`` column stores a 1024-dimensional vector generated by
    the vroom-embedding service (AITeamVN/Vietnamese_Embedding_v2).
    """

    __tablename__ = "employee_knowledge_base_chunks"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    document_id: uuid.UUID = Field(
        foreign_key="employee_knowledge_base_documents.id",
    )
    chunk_index: int
    content: str = Field(sa_column=Column(Text, nullable=False))
    embedding: Optional[list[float]] = Field(
        default=None,
        sa_column=Column(Vector(1024), nullable=True),
    )
    token_count: int = Field(default=0)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        sa_column=Column(DateTime(timezone=True), nullable=False),
    )
