/**
 * @deprecated Import from '@/components/shared-ui' instead.
 * Re-exports kept temporarily for backward compatibility.
 * Will be removed in a future cleanup.
 */
export {
  ErrorBanner,
  ErrorAlert,
  Loading,
  LoadingRows,
  EmptyState,
  StatusPill,
  Badge,
  statusTone,
  CANDIDATE_STATUS_META,
  INBOX_STATUS_META,
  JOB_STATUS_META,
  CONFLICT_STATUS_META,
  AUDIT_ACTION_LABELS,
  MIME_TYPE_LABELS,
  SERVICE_LABELS,
  PageHeader,
  Card,
  SectionTitle,
  Field,
  TextInput,
  TextArea,
  Select,
  ButtonPrimary,
  ButtonGhost,
  ButtonDanger,
  Modal,
  formatVND,
  formatDateTime,
  formatDate,
  formatRuntimeDetail,
  formatLatency,
  formatAuditDetails,
  confidencePct,
} from '@/components/shared-ui';
