"""Add manager_id to employee

Revision ID: 039
Revises: 038
Create Date: 2026-06-12 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '039'
down_revision = '038'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('manager_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_employees_manager_id', 'employees', 'employees', ['manager_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_employees_manager_id', 'employees', type_='foreignkey')
    op.drop_column('employees', 'manager_id')
    # ### end Alembic commands ###
