import {
  BarChart3,
  Bot,
  Briefcase,
  Building2,
  Calendar,
  CalendarOff,
  Clock,
  DollarSign,
  FileSearch,
  Gift,
  ListChecks,
  Mail,
  PartyPopper,
  Receipt,
  ScrollText,
  Shield,
  Settings,
  Timer,
  Upload,
  UserCog,
  Users,
  UserSearch,
} from 'lucide-react';
import type { HeaderNavConfig } from './header-nav-config';

export const adminNavConfig: HeaderNavConfig = {
  logo: { label: 'Vroom', href: '/' },
  groups: [
    {
      id: 'nhan-su',
      label: 'Nhân sự',
      links: [
        { href: '/employees', label: 'Danh sách NV', icon: Users },
        { href: '/settings/departments', label: 'Phòng ban', icon: Building2 },
        { href: '/settings/positions', label: 'Chức vụ', icon: Briefcase },
        { href: '/employees/import', label: 'Import', icon: Upload },
      ],
      activeRoutes: ['/employees', '/settings/departments', '/settings/positions'],
    },
    {
      id: 'tuyen-dung',
      label: 'Tuyển dụng',
      links: [
        { href: '/recruitment', label: 'Pipeline', icon: UserSearch },
        { href: '/recruitment/job-openings', label: 'Vị trí TD', icon: Briefcase },
        { href: '/onboarding', label: 'Onboarding', icon: ListChecks },
        { href: '/recruitment/candidates', label: 'Ứng viên', icon: Users },
        { href: '/recruitment/metrics', label: 'Metrics', icon: BarChart3 },
        { href: '/recruitment/review', label: 'Review', icon: FileSearch },
      ],
      activeRoutes: ['/recruitment'],
    },
    {
      id: 'cham-cong',
      label: 'Chấm công',
      links: [
        { href: '/attendance', label: 'Danh sách', icon: Clock },
        { href: '/attendance/schedules', label: 'Lịch làm', icon: Calendar },
        { href: '/attendance/leave', label: 'Nghỉ phép', icon: CalendarOff },
        { href: '/attendance/overtime', label: 'Tăng ca', icon: Timer },
        { href: '/attendance/holidays', label: 'Ngày lễ', icon: PartyPopper },
      ],
      activeRoutes: ['/attendance'],
    },
    {
      id: 'luong',
      label: 'Lương',
      links: [
        { href: '/payroll', label: 'Bảng lương', icon: DollarSign },
        { href: '/payroll/config', label: 'Cấu hình', icon: Settings },
        { href: '/payroll/allowances', label: 'Phụ cấp', icon: Gift },
        { href: '/payroll/tax', label: 'Thuế', icon: Receipt },
      ],
      activeRoutes: ['/payroll'],
    },
    {
      id: 'he-thong',
      label: 'Hệ thống',
      links: [
        { href: '/admin/users', label: 'Users', icon: UserCog },
        { href: '/admin/audit-logs', label: 'Audit logs', icon: ScrollText },
        { href: '/admin/assistant', label: 'AI Assistant', icon: Bot },
        { href: '/admin/assistant-tools', label: 'AI Tools Config', icon: Bot },
        { href: '/gmail', label: 'Gmail', icon: Mail },
        { href: '/settings/organization', label: 'Cấu hình mạng', icon: Shield },
      ],
      activeRoutes: ['/admin', '/gmail', '/settings/organization'],
    },
  ],
};
